default: &default
  host: <%= Rails.application.credentials.salesforce.host %>
  client_id: <%= Rails.application.credentials.salesforce.client_id %>
  client_secret: <%= Rails.application.credentials.salesforce.client_secret %>
  api_version: <%= Rails.application.credentials.salesforce.api_version %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  host: login.salesforce.com